from app.conditions import BaseType, StackSize
from app.actions import TierStyle
from app.blocks import Show, Hide
from app.categories import CURRENCY, TIER

config = {
    CURRENCY.TRANSMUTATION: TIER.COMMON,
    CURRENCY.AUGMENTATION: TIER.COMMON,
    CURRENCY.ALCHEMY: TIER.RARE,
    CURRENCY.REGAL: TIER.RARE,
    CURRENCY.CHAOS: TIER.LEGENDARY,
    CURRENCY.VAAL: TIER.RARE,
    CURRENCY.EXALTED: TIER.LEGENDARY,
    CURRENCY.DIVINE: TIER.LEGENDARY,
    CURRENCY.ANNULMENT: TIER.LEGENDARY,
    CURRENCY.CHANCE: TIER.LEGENDARY,
    CURRENCY.MIRROR: TIER.LEGENDARY,
    CURRENCY.ARCANIST: TIER.COMMON,
    CURRENCY.ARMOURER: TIER.COMMON,
    CURRENCY.BLACKSMITH: TIER.COMMON,
    CURRENCY.ARTIFICER: TIER.COMMON,
    CURRENCY.GEMCUTTER: TIER.COMMON,
    CURRENCY.GLASSBLOWER: TIER.COMMON,
    CURRENCY.LESSER_JEWELLER: TIER.RARE,
    CURRENCY.GREATER_JEWELLER: TIER.EPIC,
    CURRENCY.PERFECT_JEWELLER: TIER.LEGENDARY,
    CURRENCY.ARTIFICERS_SHARD: TIER.COMMON,
    CURRENCY.TRANSMUTATION_SHARD: TIER.COMMON,
    CURRENCY.REGAL_SHARD: TIER.RARE,
    CURRENCY.CHANCE_SHARD: TIER.EPIC,
}

currency_rules = [
    Show([BaseType(name), TierStyle(tier)]) for name, tier in config.items()
]

rules = [
    *currency_rules,
    Show([BaseType("Gold"), StackSize(1000)]),
    Hide([BaseType("Gold")]),
]
