from app.blocks import *
from app.actions import *
from app.conditions import *
from app.categories import *

shared_config = {
    # Tiered currency
    CURRENCY.TRANSMUTATION: TIER.RARE,
    CURRENCY.GREATER_TRANSMUTATION: TIER.EPIC,
    CURRENCY.PERFECT_TRANSMUTATION: TIER.LEGENDARY,
    CURRENCY.AUGMENTATION: TIER.RARE,
    CURRENCY.GREATER_AUGMENTATION: TIER.EPIC,
    CURRENCY.PERFECT_AUGMENTATION: TIER.LEGENDARY,
    CURRENCY.REGAL: TIER.EPIC,
    CURRENCY.GREATER_REGAL: TIER.LEGENDARY,
    CURRENCY.GREATER_REGAL: TIER.LEGENDARY,
    CURRENCY.PERFECT_REGAL: TIER.LEGENDARY,
    CURRENCY.EXALTED: TIER.EPIC,
    CURRENCY.GREATER_EXALTED: TIER.LEGENDARY,
    CURRENCY.PERFECT_EXALTED: TIER.LEGENDARY,
    CURRENCY.CHAOS: TIER.EPIC,
    CURRENCY.GREATER_CHAOS: TIER.LEGENDARY,
    CURRENCY.PERFECT_CHAOS: TIER.LEGENDARY,
    # Shard
    CURRENCY.CHANCE_SHARD: TIER.RARE,
    # CURRENCY.REGAL_SHARD: TIER.COMMON,
    # CURRENCY.ARTIFICERS_SHARD: TIER.RARE,
    # quality
    CURRENCY.ARTIFICER: TIER.RARE,
    CURRENCY.GEMCUTTER: TIER.EPIC,
    CURRENCY.ARCANIST: TIER.COMMON,
    CURRENCY.ARMOURER: TIER.COMMON,
    CURRENCY.BLACKSMITH: TIER.COMMON,
    CURRENCY.GLASSBLOWER: TIER.COMMON,
    # Socket
    # CURRENCY.LESSER_JEWELLER: TIER.COMMON,
    CURRENCY.GREATER_JEWELLER: TIER.RARE,
    CURRENCY.PERFECT_JEWELLER: TIER.LEGENDARY,
    # Other
    CURRENCY.VAAL: TIER.EPIC,
    CURRENCY.ALCHEMY: TIER.EPIC,
    # Tink
    CURRENCY.CHANCE: TIER.LEGENDARY,
    CURRENCY.DIVINE: TIER.LEGENDARY,
    CURRENCY.MIRROR: TIER.LEGENDARY,
    CURRENCY.HINEKORA: TIER.LEGENDARY,
    CURRENCY.ANNULMENT: TIER.LEGENDARY,
    CURRENCY.FRACTURING: TIER.LEGENDARY,
}

rules = []
rules.extend(
    Show([BaseType(currency), TierStyle(tier)])
    for currency, tier in shared_config.items()
)

rules.append(Hide([MultiBaseType(["Gold", CURRENCY.WISDOM, CURRENCY.REGAL_SHARD])]))
